#有效用户最小数据量，小于此数据量的用户被视为无效用户，无法统计其od点
minUserInfoSize: 200
#用户每趟行程的最小时间间隔单位秒，小于此时间间隔，说明用户没有行程，或者计算有误
minInterval: 600
#用户每趟行程的最大时间间隔单位秒，大于此时间间隔，说明用户没有行程，或者计算有误，用户行程不在统计范围内
maxInterval: 18000
#用户od每个点最小数据量，在od点小于此数据量，则说明该od点判定不可靠
odInfoSize: 200